Change user hyper tag with UBID
ubicloud/ubicloud pull request #1180
Opened 2024-02-05 12:36 UTC by enescakir

All resources are represented in our authorization system, referred to as a "hyper tag". Each resource has a unique format, for example, users are represented as "user/test@example.com", projects as "project/pjbw1tcvkew67qcxqsjpbvh19c", and virtual machines as "project/pjcm807azyxe6ht7ct027tcg83/location/hetzner-fsn1/vm/my-vm".

We prefer using user-friendly names over UBIDs, making it easier for customers to edit their access policies. However, we identified a problem with this approach. When a resource's hyper tag changes (e.g., a user changes their email), the existing access policies need to be updated accordingly. Without such updates, permissions to resources could be affected.

Automatically updating access policies to apply these changes is not recommended. Instead, I propose keeping the resource's UBID as the hyper tag in the database, which eliminates the need for changes when resources are renamed. This is because UBIDs remain constant throughout a resource's lifetime.

We only need to map the prettified policy name when displaying or saving access policies. The authorization system uses UBIDs in the background.

I have refactored the user's hyper tag for now. I will continue to refactor other resources in subsequent PRs after the deployment of user change.

We need to update user hyper tags in production after deployment.

From a security perspective, we only transform tags/UBIDs for resources associated with this project.

2024-02-05 22:25 UTC, fdr commented
What happens when a name can't be resolved? It should error right? Maybe I missed the test for this (or it happens for free from the tests already existing?)

2024-02-06 00:44 UTC, enescakir commented
> What happens when a name can't be resolved? It should error right? Maybe I missed the test for this (or it happens for free from the tests already existing?)

If the name can't be resolved, nothing happen. The raw value is saved into policy not UBID value.

2024-02-06 13:49 UTC, byucesoy commented on model/account.rb
> +  def to_policy(project = nil)
Do we need project here?

2024-02-06 13:50 UTC, byucesoy commented on model/account.rb
> +  def to_policy(project = nil)
to_policy_text or to_policy_label (i.e. something that doesn't refer to the whole policy) maybe?

2024-02-06 13:52 UTC, byucesoy commented on model/account.rb
> +  def to_policy(project = nil)
actually, we don't use "to_" prefix in hyper_tag_name. Maybe just policy_test/policy_label/policy_something?

2024-02-06 13:53 UTC, byucesoy reviewed
I agree on erroring out on missing users. Other than that looks good.

2024-02-07 08:33 UTC, fdr requested changes
I guess @byucesoy and I are in agreement that, unless there is additional justification, a less interesting behavior for when identifiers get bound to ubids or not seems like something to do

2024-02-08 11:42 UTC, enescakir commented
I added a check for user existence.

2024-02-10 15:21 UTC, byucesoy approved these changes

2024-02-12 22:21 UTC, fdr approved these changes
I see you put in the error for users, but does it not apply to any named resource? The lexical/dynamic binding confusing applies to all of them. But perhaps we can engage one problem at a time (and remove the filter if we see no problems)

2024-10-16 11:28 UTC, enescakir commented
It was a PoC. We need to do it for all resources.

2024-10-16 11:28 UTC, closed without merging