Add mapping from display location name to internal location name
ubicloud/ubicloud pull request #1421
Opened 2024-04-03 02:11 UTC by velioglu

In order to show location names on URIs like `eu-central-h1` instead of `hetzner-fsn1`, mapping have been added. So, users will send a request to the display locations but internally we will use internal names on the code.

To make handling provider and location information from a single point and easily, `provider_information.yml` is added. After this commit, provider and location information will be populated dynamically. So, if a new region wants to be added, it will be enough updating that file only.

2024-04-10 08:48 UTC, furkansahin reviewed
I understand this is a change that touches many places at the same time. However, it's difficult to review this change in this format. Is it possible to split the code into multiple commits related to different parts of the codebase? Like core change, pg specific commit, VM specific commit, etc. You can put all the test changes to very end if it makes it easier.

2024-04-12 08:31 UTC, velioglu commented
@furkansahin I've divided the change into separate commits.

2024-04-18 19:02 UTC, enescakir requested changes
The location is used in the hyper tag for some resources. Since the customer doesn't aware of internal location name, we need to use display locations in the hyper tags too. Also we need to migrate them in production.

```
  def hyper_tag_name(project)
    "project/#{project.ubid}/location/#{location}/vm/#{name}"
  end
```

2024-04-19 14:09 UTC, furkansahin commented on lib/option.rb
> +  provider_information = YAML.load_file("config/provider_information.yml")
let's add `require "yaml"` to the start of the file. Otherwise, this fails in my local.

2024-04-21 03:51 UTC, velioglu commented on config/provider_information.yml
> +    provider_internal_name: hetzner,
I do want to keep keywords (both here and parser) for provider and location. Let me keep it as it is.

2024-04-21 03:53 UTC, velioglu commented on lib/option.rb
> +    end
one-liner requires read twice to get it (at least for me), so let me keep it as it is.

2024-04-22 19:49 UTC, enescakir approved these changes

2024-04-23 19:57 UTC, velioglu commented on lib/location_name_converter.rb
> +module LocationNameConverter
Per discussion offline, we'll be simplifying Provider and Option mapping with a subsequent PR. (It is same for the next 2 comments)

2024-04-24 08:46 UTC, merged