Enable autoload for clover app at dev
ubicloud/ubicloud pull request #194
Opened 2023-06-07 13:11 UTC by enescakir

We have some `Unreloader.autoload` directives, but autoload isn't enabled. It works similar to `require` when not enabled. Autoload speeds things up at dev, or when only running a subset of tests. If the constants are not accessed, you don’t need to pay the cost of loading the related files.

Autoloading hash branches is little bit tricky. Of course Jeremy has `autoload_hash_branches` plugin and it accepts directories too. `autoload_hash_branch_dir` expects filename and hash branches to be same. But filenames use `_` and hash branches use `-` as separator. Because of that we autoload files one by one instead of using `autoload_hash_branch_dir`.

2023-06-07 13:14 UTC, enescakir commented on clover.rb
> -unless defined?(Unreloader)
Normally we define `Unreloader` in `config.ru`. But rspec uses Clover directly without `config.ru`. We need this redefining only for tests, so I moved it to spec_helper

2023-06-07 18:03 UTC, fdr approved these changes
Yeah, we just need to go through all our loading stuff and simplify/improve it quite a bit...and probably eliminate Zeitwerk. This seems like it moves us in that general direction.

2023-06-08 01:07 UTC, fdr commented
Alright well I have a patch to change loader.rb to use unreloader, plz hold

2023-06-09 00:13 UTC, fdr requested changes
Okay, this can't work now that I look more closely. The problem is TagSpaceShadow and other Shadow classes are referenced from outside their respective files, and also, the constant name one is obliged to provide from the autoload block is omitted. In order to get this kind of lazy loading to work, we'd want to be be able to know the constant name using very fast calls to, say, readdir or stat, and the file structure is not rich enough to let us do this at the moment.

2023-06-09 06:21 UTC, enescakir commented
I will enable it when I move out `Shadow`s from routes.

2023-06-09 06:21 UTC, closed without merging