Refactor load balancer post api
ubicloud/ubicloud pull request #2278
Opened 2024-11-18 23:10 UTC by enescakir

- **Refactor load balancer post api**
  We create/retrieve location-based resources using
  `project/<P>/location/<L>/vm/<NAME>` pattern [^1]. However, the load
  balancer deviates from this pattern. We retrieve the load balancer with
  `project/<P>/location/<L>/load-balancer/<NAME>`, but create it with
  `project/<P>/load-balancer/<NAME>`. This is because we get the location
  from the private subnet's location.  Also `attach-vm`/`detach-vm`
  endpoints have the location in the path.
  
  We should align it with other resources to maintain consistency for
  location-based resources. We use the location information from the path
  to validate the private subnet's location. It can't find private subnet
  if the locations don't match.
  
  [^1]: https://www.ubicloud.com/docs/api-reference/overview#creating-resources
  

- **Add load balancer post route for invalid names**
  If the resource name doesn't match the NAME_OR_UBID pattern, we should
  return an appropriate error. We have a similar route in other resources
  too.
  

- **Use TEST_LOCATION in load balancer API tests**
  It makes easier to keep locations same
  

- **Remove unnecessary load balancer test**
  It's already tested at
  spec/routes/api/project/location/load_balancer_spec.rb

2024-11-18 23:12 UTC, enescakir commented
@geemus What do you think about 828fd359ec4cd5c74c53ba6fda403f7b6e930198?

2024-11-18 23:20 UTC, jeremyevans requested changes
Looks good!  My understanding is we haven't promised backwards compatibility for the API yet, so this should be fine after the one requested change.

2024-11-18 23:20 UTC, jeremyevans commented on routes/merged/project/load_balancer.rb
> +      r.post do
```suggestion
      r.post true do
```

Otherwise the route would accept arbitrary garbage in the remaining path.

2024-11-19 00:49 UTC, fdr commented
Well, approval modulo @jeremyevans 's spotted bug

2024-11-19 11:42 UTC, enescakir commented
> Looks good! My understanding is we haven't promised backwards compatibility for the API yet, so this should be fine after the one requested change.

Since it's not included in our API documentation, I think we haven't made any specific promises to anyone.
https://www.ubicloud.com/docs/api-reference/overview

2024-11-19 13:48 UTC, geemus commented
LGTM. Yeah, since you haven't explicitly promised anything yet, breaking changes are probably fine for the time being at least. Though it might be good to explicitly say that nothing is promised to be clear.

2024-11-19 19:38 UTC, jeremyevans approved these changes

2024-11-20 11:26 UTC, merged